// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using AutoMLML.Model;

namespace AutoMLML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"C:\Projects\Attestation\AutoML\products.stats.csv";

        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Next with predicted Next from sample data...\n\n");
            Console.WriteLine($"productId: {sampleData.ProductId}");
            Console.WriteLine($"year: {sampleData.Year}");
            Console.WriteLine($"month: {sampleData.Month}");
            Console.WriteLine($"units: {sampleData.Units}");
            Console.WriteLine($"avg: {sampleData.Avg}");
            Console.WriteLine($"count: {sampleData.Count}");
            Console.WriteLine($"max: {sampleData.Max}");
            Console.WriteLine($"min: {sampleData.Min}");
            Console.WriteLine($"prev: {sampleData.Prev}");
            Console.WriteLine($"\n\nActual Next: {sampleData.Next} \nPredicted Next: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
