// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace AutoML.ConsoleManualTraining
{
    public class ModelInput
    {
        [ColumnName("next"), LoadColumn(0)]
        public float Next { get; set; }


        [ColumnName("productId"), LoadColumn(1)]
        public float ProductId { get; set; }


        [ColumnName("year"), LoadColumn(2)]
        public float Year { get; set; }


        [ColumnName("month"), LoadColumn(3)]
        public float Month { get; set; }


        [ColumnName("units"), LoadColumn(4)]
        public float Units { get; set; }


        [ColumnName("avg"), LoadColumn(5)]
        public float Avg { get; set; }


        [ColumnName("count"), LoadColumn(6)]
        public float Count { get; set; }


        [ColumnName("max"), LoadColumn(7)]
        public float Max { get; set; }


        [ColumnName("min"), LoadColumn(8)]
        public float Min { get; set; }


        [ColumnName("prev"), LoadColumn(9)]
        public float Prev { get; set; }


    }
}
